inherit_from:
  - .rubocop_todo.yml

AllCops:
  RunRailsCops: true # always run the rails cops

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

# Allow longer lines
Metrics/LineLength:
  Max: 385

# Allow larger Assignment Branch Condition size
Metrics/AbcSize:
    Max: 114

Metrics/MethodLength:
  Max: 20
